import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"
import { rupiah, formatDate } from "@/lib/utils"
import { redirect } from "next/navigation"
import Link from "next/link"

export default async function BillsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const session = await auth(); if (!session?.user) redirect("/login")
  const { q = "", status = "SEMUA" } = await searchParams
  const memberFilter = session.user.role === "ANGGOTA" ? { userId: session.user.id } : q ? { user: { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { username: { contains: q, mode: "insensitive" as const } }] } } : {}
  const payments = await prisma.billPayment.findMany({ where: { ...memberFilter, ...(status === "LUNAS" ? { status: "LUNAS" } : status === "BELUM_LUNAS" ? { status: "BELUM_LUNAS" } : {}) }, include: { user: true, bill: true }, orderBy: [{ paidAt: "desc" }, { user: { name: "asc" } }] })
  const counts = { all: payments.length, paid: payments.filter(p=>p.status==="LUNAS").length, unpaid: payments.filter(p=>p.status==="BELUM_LUNAS").length }
  return <main className="min-h-screen bg-slate-950 p-5 text-slate-100 md:p-10"><div className="mx-auto max-w-6xl"><Link className="text-sm text-emerald-400" href="/dashboard">← Dashboard</Link><div className="mt-5 flex flex-wrap justify-between gap-4"><div><p className="text-sm text-emerald-400">TAGIHAN</p><h1 className="text-3xl font-bold">Status pembayaran</h1></div><div className="rounded-xl bg-slate-900 px-4 py-3 text-sm">Lunas: <b className="text-emerald-400">{counts.paid}</b> / {counts.all}</div></div>{session.user.role !== "ANGGOTA" && <form className="mt-7 flex gap-3"><input name="q" defaultValue={q} placeholder="Cari nama atau username..." className="w-full rounded-xl border border-slate-700 bg-slate-900 px-4 py-3"/><button className="rounded-xl bg-emerald-400 px-5 font-bold text-slate-950">Cari</button></form>}<nav className="mt-5 flex gap-2">{[["SEMUA",counts.all],["BELUM_LUNAS",counts.unpaid],["LUNAS",counts.paid]].map(([s,n])=><Link key={String(s)} href={`/tagihan?status=${s}${q?`&q=${q}`:""}`} className={`rounded-full px-4 py-2 text-sm ${status===s?"bg-emerald-400 text-slate-950":"bg-slate-800 text-slate-300"}`}>{String(s).replace("_"," ")} ({n})</Link>)}</nav><div className="mt-5 overflow-hidden rounded-2xl border border-slate-800"><table className="w-full text-left text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-4">Nama</th><th>Tagihan</th><th>Status</th><th className="hidden sm:table-cell">Tanggal bayar</th><th>Nominal</th></tr></thead><tbody>{payments.map(p=><tr key={p.id} className="border-t border-slate-800"><td className="p-4"><b>{p.user.name}</b><span className="block text-xs text-slate-500">@{p.user.username}</span></td><td>{p.bill.name}</td><td><span className={p.status==="LUNAS"?"text-emerald-400":"text-amber-300"}>{p.status.replace("_"," ")}</span></td><td className="hidden sm:table-cell text-slate-400">{formatDate(p.paidAt)}</td><td>{rupiah(Number(p.bill.amount))}</td></tr>)}</tbody></table>{!payments.length && <p className="p-10 text-center text-slate-500">Tidak ada data yang sesuai.</p>}</div></div></main>
}
