import { auth } from "@/auth"
import { prisma } from "@/lib/prisma"
import { rupiah, formatDate } from "@/lib/utils"
import Link from "next/link"
import { redirect } from "next/navigation"

export default async function Dashboard() {
  const session = await auth(); if (!session?.user) redirect("/login")
  const [members, bills, paid, expenses, latest] = await Promise.all([
    prisma.user.count(), prisma.bill.count({ where: { isActive: true } }), prisma.billPayment.findMany({ where: { status: "LUNAS" }, include: { bill: true } }), prisma.expense.findMany(), prisma.billPayment.findMany({ where: { userId: session.user.id }, include: { bill: true }, orderBy: { paidAt: "desc" }, take: 5 }),
  ])
  const income = paid.reduce((total, item) => total + Number(item.bill.amount), 0), expense = expenses.reduce((total, item) => total + Number(item.amount), 0)
  const outstanding = session.user.role === "ANGGOTA" ? await prisma.billPayment.count({ where: { userId: session.user.id, status: "BELUM_LUNAS" } }) : await prisma.billPayment.count({ where: { status: "BELUM_LUNAS" } })
  const cards = [{ label: "Saldo Kas", value: rupiah(income-expense) }, { label: "Tagihan Aktif", value: String(bills) }, { label: "Total Pemasukan", value: rupiah(income) }, { label: "Belum Lunas", value: String(outstanding) }]
  return <main className="min-h-screen bg-slate-950 text-slate-100"><header className="border-b border-slate-800 px-5 py-4 md:px-10"><div className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/dashboard" className="font-bold tracking-tight text-emerald-400">◉ CLASSPAY</Link><div className="text-right text-sm"><p className="font-medium">{session.user.name}</p><p className="text-xs text-slate-400">{session.user.role}</p></div></div></header><section className="mx-auto max-w-6xl p-5 md:p-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-emerald-400">RINGKASAN KELAS</p><h1 className="mt-1 text-3xl font-bold">Selamat datang, {session.user.name?.split(" ")[0]}</h1><p className="mt-2 text-slate-400">Kelola kas kelas dengan jelas dan teratur.</p></div>{session.user.role !== "ANGGOTA" && <Link className="rounded-xl bg-emerald-400 px-4 py-3 text-sm font-bold text-slate-950" href="/tagihan">Kelola tagihan →</Link>}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(c=><div key={c.label} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-400">{c.label}</p><p className="mt-3 text-2xl font-bold">{c.value}</p></div>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6 lg:col-span-2"><h2 className="font-bold">Pembayaran terbaru</h2><div className="mt-4 space-y-3">{latest.length ? latest.map(p=><div className="flex items-center justify-between border-b border-slate-800 pb-3" key={p.id}><div><p>{p.bill.name}</p><p className="text-xs text-slate-400">{formatDate(p.paidAt)}</p></div><span className={p.status === "LUNAS" ? "rounded-full bg-emerald-400/15 px-3 py-1 text-xs text-emerald-400" : "rounded-full bg-amber-400/15 px-3 py-1 text-xs text-amber-300"}>{p.status.replace("_", " ")}</span></div>) : <p className="py-10 text-center text-sm text-slate-500">Belum ada pembayaran.</p>}</div></section><aside className="rounded-2xl border border-slate-800 bg-gradient-to-b from-emerald-400/15 to-slate-900 p-6"><h2 className="font-bold">Akses cepat</h2><p className="mt-2 text-sm text-slate-400">{session.user.role === "ANGGOTA" ? "Lihat status tagihan Anda." : `${members} anggota terdaftar di kelas.`}</p><Link className="mt-6 block rounded-xl border border-slate-700 p-3 text-center text-sm hover:bg-slate-800" href="/tagihan">Lihat semua tagihan</Link></aside></div></section></main>
}
